In [1]:
!pip install transformers torch torchvision torchaudio numpy pandas tqdm matplotlib huggingface_hub datasets evaluate scikit-learn accelerate

Requirement already satisfied: transformers in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (4.57.1)
Requirement already satisfied: torch in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (2.8.0)
Requirement already satisfied: torchvision in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (0.23.0)
Requirement already satisfied: torchaudio in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (2.8.0)
Requirement already satisfied: numpy in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (2.0.2)
Requirement already satisfied: pandas in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: tqdm in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (4.67.1)
Requirement already satisfied: matplotlib in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: huggingface_hub in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (0.35.3)
Requirement already satisfied: datasets in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (4.2.0)
Requirement already satisfied: evaluate in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (0.4.6)
Requirement already satisfied: scikit-learn in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (1.6.1)
Requirement already satisfied: accelerate in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (1.10.1)
Requirement already satisfied: filelock in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from transformers) (3.19.1)
Requirement already satisfied: packaging>=20.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from transformers) (2025.9.18)
Requirement already satisfied: requests in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from transformers) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from huggingface_hub) (2025.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from huggingface_hub) (1.1.10)
Requirement already satisfied: sympy>=1.13.3 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from torch) (3.1.6)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from torchvision) (11.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: pyarrow>=21.0.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from datasets) (0.4.0)
Requirement already satisfied: httpx<1.0.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.13.1)
Requirement already satisfied: anyio in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: scipy>=1.6.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: psutil in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from accelerate) (7.1.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: zipp>=3.1.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages (from jinja2->torch) (3.0.3)

In [2]:
import sys
import os

# Path to the folder you want to add
subfolder_path = os.path.join(os.getcwd(), "roberta_classifier")

# Add it to sys.path
if subfolder_path not in sys.path:
    sys.path.append(subfolder_path)

In [ ]:
import json
import os
import torch
import sys
import numpy as np
import pandas as pd
from transformers import (
    AutoModelForSequenceClassification,
)

from roberta_classifier.dataset import prepare_datasets
from roberta_classifier.train import train_binary, evaluate_binary
from roberta_classifier.finetuning import save_results, sampling_tuning
from roberta_classifier.seeding import enforce_reproducibility
from roberta_classifier.result_handling import get_balanced_top_configs

results_dir = "roberta_classifier_results"
model_name = "FacebookAI/xlm-roberta-base"
file_base = "_tuning_metrics.csv"

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
language = "ko"
oversample_ratio, undersample_ratio = get_balanced_top_configs(f"{results_dir}/{language}{file_base}")

enforce_reproducibility(42)

# ==== PREPARE DATASETS ====
train_set, val_set, test_sets, tokenizer = prepare_datasets(model_name, oversample_ratio, undersample_ratio, language)

# ==== MODEL ====
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, 
    num_labels=2
)

# ==== TRAIN MODEL ====
model, tokenizer, epoch_history = train_binary(model, train_set, val_set, tokenizer, 1, results_dir)

# ==== EVALUATE MODEL ====
eval_results = evaluate_binary(model, tokenizer, test_sets[language])

# ==== SAVE RESULTS & MODEL ====
save_results(results_dir, language, epoch_history, eval_results)

=== Top Balanced Sampling Configurations ===
╒═════════════════╤══════════════════╤════════════╤═════════════════╤══════════════════╤══════════╤═════════════════╕
│   over_sampling │   under_sampling │   accuracy │   true_accuracy │   false_accuracy │     loss │   balance_score │
╞═════════════════╪══════════════════╪════════════╪═════════════════╪══════════════════╪══════════╪═════════════════╡
│               1 │              0   │   0.980337 │        0.991098 │         0.789474 │ 0.151025 │        0.961543 │
├─────────────────┼──────────────────┼────────────┼─────────────────┼──────────────────┼──────────┼─────────────────┤
│               1 │              1   │   0.980337 │        0.991098 │         0.789474 │ 0.151025 │        0.961543 │
├─────────────────┼──────────────────┼────────────┼─────────────────┼──────────────────┼──────────┼─────────────────┤
│               1 │              0.5 │   0.966292 │        0.976261 │         0.789474 │ 0.21263  │        0.905296 │
╘═════════════════╧══════════════════╧════════════╧═════════════════╧══════════════════╧══════════╧═════════════════╛
[2025-10-25 09:17:04,009] - [INFO] - Original Train dataset class split: Counter({1: 2122, 0: 57}), with a total of 2179 samples
[2025-10-25 09:17:04,112] - [INFO] - Sampled Train dataset class split: Counter({1: 2122, 0: 2122}), with a total of 4244 samples
[2025-10-25 09:17:04,117] - [INFO] - Validation dataset class split: Counter({1: 237, 0: 6}), with a total of 243 samples
[2025-10-25 09:17:04,120] - [INFO] - Test dataset class split: Counter({1: 337, 0: 19}), with a total of 356 samples

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

53.0
[2025-10-25 09:17:07,041] - [INFO] - Starting training of model (answerability classification).

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

[2025-10-25 09:22:36,814] - [INFO] - Training completed.
[2025-10-25 09:22:36,827] - [INFO] - Running evaluation...

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

[2025-10-25 09:22:41,308] - [INFO] - Evaluation Results:
[2025-10-25 09:22:41,308] - [INFO] - eval_loss: 0.17167022824287415
[2025-10-25 09:22:41,308] - [INFO] - eval_model_preparation_time: 0.0011
[2025-10-25 09:22:41,309] - [INFO] - eval_accuracy: 0.9691011235955056
[2025-10-25 09:22:41,309] - [INFO] - eval_precision: 0.9939393939393939
[2025-10-25 09:22:41,309] - [INFO] - eval_recall: 0.973293768545994
[2025-10-25 09:22:41,309] - [INFO] - eval_f1: 0.9835082458770614
[2025-10-25 09:22:41,309] - [INFO] - eval_confusion_matrix: [17, 2, 9, 328]
[2025-10-25 09:22:41,309] - [INFO] - eval_runtime: 4.478
[2025-10-25 09:22:41,310] - [INFO] - eval_samples_per_second: 79.5
[2025-10-25 09:22:41,310] - [INFO] - eval_steps_per_second: 10.049
[2025-10-25 09:22:41,315] - [INFO] - Saved per-epoch metrics at: roberta_classifier_results/ko_train_metrics_per_epoch.csv
[2025-10-25 09:22:41,501] - [INFO] - Saved test metrics at: roberta_classifier_results/ko_test_evaluation_metrics.csv

In [ ]:
language = "ar"
oversample_ratio, undersample_ratio = get_balanced_top_configs(f"{results_dir}/{language}{file_base}")

enforce_reproducibility(42)

# ==== PREPARE DATASETS ====
train_set, val_set, test_sets, tokenizer = prepare_datasets(model_name, oversample_ratio, undersample_ratio, language)

# ==== MODEL ====
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, 
    num_labels=2
)

# ==== TRAIN MODEL ====
model, tokenizer, epoch_history = train_binary(model, train_set, val_set, tokenizer, 1, results_dir)

# ==== EVALUATE MODEL ====
eval_results = evaluate_binary(model, tokenizer, test_sets[language])

# ==== SAVE RESULTS & MODEL ====
save_results(results_dir, language, epoch_history, eval_results)

=== Top Balanced Sampling Configurations ===
╒═════════════════╤══════════════════╤════════════╤═════════════════╤══════════════════╤═══════════╤═════════════════╕
│   over_sampling │   under_sampling │   accuracy │   true_accuracy │   false_accuracy │      loss │   balance_score │
╞═════════════════╪══════════════════╪════════════╪═════════════════╪══════════════════╪═══════════╪═════════════════╡
│            0.5  │              0.5 │   0.983133 │        0.983471 │         0.980769 │ 0.0947132 │        1        │
├─────────────────┼──────────────────┼────────────┼─────────────────┼──────────────────┼───────────┼─────────────────┤
│            1    │              0.5 │   0.980723 │        0.983471 │         0.961538 │ 0.108005  │        0.987334 │
├─────────────────┼──────────────────┼────────────┼─────────────────┼──────────────────┼───────────┼─────────────────┤
│            0.25 │              0   │   0.978313 │        0.980716 │         0.961538 │ 0.0983243 │        0.972187 │
╘═════════════════╧══════════════════╧════════════╧═════════════════╧══════════════════╧═══════════╧═════════════════╛
[2025-10-25 09:22:44,739] - [INFO] - Original Train dataset class split: Counter({1: 2073, 0: 229}), with a total of 2302 samples
[2025-10-25 09:22:44,824] - [INFO] - Sampled Train dataset class split: Counter({0: 1036, 1: 1036}), with a total of 2072 samples
[2025-10-25 09:22:44,830] - [INFO] - Validation dataset class split: Counter({1: 230, 0: 26}), with a total of 256 samples
[2025-10-25 09:22:44,833] - [INFO] - Test dataset class split: Counter({1: 363, 0: 52}), with a total of 415 samples

Map: 100%|██████████| 256/256 [00:00<00:00, 5611.20 examples/s]
Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

25.0
[2025-10-25 09:22:47,402] - [INFO] - Starting training of model (answerability classification).

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

[2025-10-25 09:26:34,281] - [INFO] - Training completed.
[2025-10-25 09:26:34,298] - [INFO] - Running evaluation...

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

[2025-10-25 09:26:40,199] - [INFO] - Evaluation Results:
[2025-10-25 09:26:40,199] - [INFO] - eval_loss: 0.11639081686735153
[2025-10-25 09:26:40,199] - [INFO] - eval_model_preparation_time: 0.0013
[2025-10-25 09:26:40,199] - [INFO] - eval_accuracy: 0.980722891566265
[2025-10-25 09:26:40,200] - [INFO] - eval_precision: 0.9944289693593314
[2025-10-25 09:26:40,200] - [INFO] - eval_recall: 0.9834710743801653
[2025-10-25 09:26:40,200] - [INFO] - eval_f1: 0.9889196675900277
[2025-10-25 09:26:40,200] - [INFO] - eval_confusion_matrix: [50, 2, 6, 357]
[2025-10-25 09:26:40,200] - [INFO] - eval_runtime: 5.897
[2025-10-25 09:26:40,200] - [INFO] - eval_samples_per_second: 70.375
[2025-10-25 09:26:40,200] - [INFO] - eval_steps_per_second: 8.818
[2025-10-25 09:26:40,203] - [INFO] - Saved per-epoch metrics at: roberta_classifier_results/ar_train_metrics_per_epoch.csv
[2025-10-25 09:26:40,267] - [INFO] - Saved test metrics at: roberta_classifier_results/ar_test_evaluation_metrics.csv

In [ ]:
language = "te"
oversample_ratio, undersample_ratio = get_balanced_top_configs(f"{results_dir}/{language}{file_base}")

enforce_reproducibility(42)

# ==== PREPARE DATASETS ====
train_set, val_set, test_sets, tokenizer = prepare_datasets(model_name, oversample_ratio, undersample_ratio, language)

# ==== MODEL ====
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, 
    num_labels=2
)

# ==== TRAIN MODEL ====
model, tokenizer, epoch_history = train_binary(model, train_set, val_set, tokenizer, 4, results_dir)

# ==== EVALUATE MODEL ====
eval_results = evaluate_binary(model, tokenizer, test_sets[language])

# ==== SAVE RESULTS & MODEL ====
save_results(results_dir, language, epoch_history, eval_results)

=== Top Balanced Sampling Configurations ===
╒═════════════════╤══════════════════╤════════════╤═════════════════╤══════════════════╤══════════╤═════════════════╕
│   over_sampling │   under_sampling │   accuracy │   true_accuracy │   false_accuracy │     loss │   balance_score │
╞═════════════════╪══════════════════╪════════════╪═════════════════╪══════════════════╪══════════╪═════════════════╡
│             0.5 │              0   │   0.796875 │        0.945017 │         0.333333 │ 0.980083 │        0.695568 │
├─────────────────┼──────────────────┼────────────┼─────────────────┼──────────────────┼──────────┼─────────────────┤
│             0.5 │              1   │   0.796875 │        0.945017 │         0.333333 │ 0.980083 │        0.695568 │
├─────────────────┼──────────────────┼────────────┼─────────────────┼──────────────────┼──────────┼─────────────────┤
│             1   │              0.5 │   0.710938 │        0.810997 │         0.397849 │ 0.927126 │        0.663236 │
╘═════════════════╧══════════════════╧════════════╧═════════════════╧══════════════════╧══════════╧═════════════════╛
[2025-10-25 09:35:28,280] - [INFO] - Original Train dataset class split: Counter({1: 1179, 0: 40}), with a total of 1219 samples
[2025-10-25 09:35:28,334] - [INFO] - Sampled Train dataset class split: Counter({1: 1179, 0: 589}), with a total of 1768 samples
[2025-10-25 09:35:28,338] - [INFO] - Validation dataset class split: Counter({1: 131, 0: 5}), with a total of 136 samples
[2025-10-25 09:35:28,341] - [INFO] - Test dataset class split: Counter({1: 291, 0: 93}), with a total of 384 samples

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

88.0
[2025-10-25 09:35:31,359] - [INFO] - Starting training of model (answerability classification).

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

[2025-10-25 09:44:11,922] - [INFO] - Training completed.
[2025-10-25 09:44:11,935] - [INFO] - Running evaluation...

/Users/xk84vl/Documents/Repos/.venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py:684: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

[2025-10-25 09:44:17,086] - [INFO] - Evaluation Results:
[2025-10-25 09:44:17,087] - [INFO] - eval_loss: 1.8895344734191895
[2025-10-25 09:44:17,087] - [INFO] - eval_model_preparation_time: 0.0014
[2025-10-25 09:44:17,087] - [INFO] - eval_accuracy: 0.7786458333333334
[2025-10-25 09:44:17,087] - [INFO] - eval_precision: 0.7959770114942529
[2025-10-25 09:44:17,087] - [INFO] - eval_recall: 0.9518900343642611
[2025-10-25 09:44:17,087] - [INFO] - eval_f1: 0.86697965571205
[2025-10-25 09:44:17,088] - [INFO] - eval_confusion_matrix: [22, 71, 14, 277]
[2025-10-25 09:44:17,088] - [INFO] - eval_runtime: 5.1475
[2025-10-25 09:44:17,088] - [INFO] - eval_samples_per_second: 74.599
[2025-10-25 09:44:17,088] - [INFO] - eval_steps_per_second: 9.325
[2025-10-25 09:44:17,090] - [INFO] - Saved per-epoch metrics at: roberta_classifier_results/te_train_metrics_per_epoch.csv
[2025-10-25 09:44:17,166] - [INFO] - Saved test metrics at: roberta_classifier_results/te_test_evaluation_metrics.csv